; PlatformIO 项目配置文件
;
;   编译选项：编译标志、源文件过滤
;   上传选项：自定义上传端口、速度和额外标志
;   库选项：依赖项、额外的库存储路径
;   高级选项：额外脚本
;
; 更多选项和示例请参阅文档
; https://docs.platformio.org/page/projectconf.html

[env:4d_systems_esp32s3_gen4_r8n16]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
monitor_speed = 115200
upload_speed = 921600
monitor_rts = 0
monitor_dtr = 0
upload_flags = 
    --before=default_reset
    --after=hard_reset
; USB CDC 需要时间重新枚举，给 2 秒延迟
monitor_open_delay = 2000
; 上传后自动打开监视器
upload_monitor = true
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=0
lib_deps = 
    fastled/FastLED@^3.9.0